services:
  - type: web
    name: toolbox-image-converter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 